apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    company: devseccops
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: external-app
      app.kubernetes.io/instance: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-app
        app.kubernetes.io/instance: nginx
    spec:
      serviceAccountName: stage-nginx-sa
      securityContext: {}
      containers:
        - name: nginx
          securityContext: {}
          image: nginx:latest
          imagePullPolicy: 'Always'
          env:
            - name: "ENVIRONMENT"
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: ENVIRONMENT
          resources:
            requests:
              memory: '256Mi'
              cpu: '200m'
            limits:
              memory: '256Mi'
              cpu: '200m'
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10

